version: 2

models:
  - name: customers
    columns:
      - name: customer_id
        test:
          - unique
          - not_null
  
  - name: stg_customers
    columns:
      - name: customer_id
        test:
          - unique
          - not_null
  
  - name: stg_orders
    columns:
      - name: order_id
        test:
          - unique
          - not_null
      - name: status
        test:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        test:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id